name: Create Release Branch

on:
  push:
    branches:
      - master

jobs:
  create_release_branch:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Git
        run: |
          git config --global user.email "cuentafrst@gmail.com"
          git config --global user.name "Armando"

      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8.6.7

      - name: Install dependencies
        run: pnpm update

      - name: Build project
        run: |
          pnpm build
          find . -name "node_modules" -type d -prune -exec rm -rf {} +

      - name: Create Release Branch
        run: |
          git checkout -b release
          git rm -rf .
          mkdir tmp-lib-dist
          rsync -av dist/lib/ tmp-lib-dist
          rm -rf dist
          rsync -av tmp-lib-dist/ .
          rm -rf tmp-lib-dist
          git add .
          git commit -m "Update release branch"

      - name: Push Release Branch
        uses: ad-m/github-push-action@v0.6.0
        with:
          branch: release
          github_token: ${{ secrets.GITHUB_TOKEN }}
          force: true
